### ISSUE TITLE
Not working on Dell S2721QS

### ISSUE THREAD

**Issue by alexpanait** [mbruggmann/osx-edid-overrides#6]
Hello,

Thanks for making the time writing this to help other people. I just tried this on a Macbook Pro 15 2017 (Big Sur) with a Dell S2721QS and it seems that in the monitor menu I still see YPbPr as color format and there are no visible improvements.

Here is the patched file:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>DisplayProductName</key>
	<string>DELL S2721QS (EDID override)</string>
	<key>edid-patches</key>
	<array>
		<dict>
			<key>offset</key>
			<integer>131</integer>
			<key>data</key>
			<data>wQ==</data>
		</dict>
	</array>
</dict>
</plist>
```

I was wondering if you have any suggestions or other things that I could try. Thank you!

Update: I'm using a HDMI cable with an Apple Multiport Adapter.

**Comment by mbruggmann** [comment]
Can you verify if the override is active in OSX? 
If you go to `About this Mac > Displays` in the menu bar while the screen is connected, does it say `DELL S2721QS (EDID override)` or `DELL S2721QS`?

**Comment by alexpanait** [comment]
> Can you verify if the override is active in OSX?
> If you go to `About this Mac > Displays` in the menu bar while the screen is connected, does it say `DELL S2721QS (EDID override)` or `DELL S2721QS`?

It was saying `DELL S2721QS (EDID override)` but in the monitor menu it was still YPbPr. I tried with a DP cable instead of adapter + HDMI and now it's RGB.

**Comment by mbruggmann** [comment]
Alright, I see. Could be that it's the multiport adapter that is messing with it, or Big Sur. But happy that you found a solution!

**Comment by alexpanait** [comment]
> Alright, I see. Could be that it's the multiport adapter that is messing with it, or Big Sur. But happy that you found a solution!

I am pretty sure it's from the adapter. Thank you for your help!
